### ISSUE TITLE
`xontrib load` error handling?

### ISSUE THREAD

**Issue by rpdelaney** [anki-code/xontrib-rc-awesome#2]
Hi! Thanks for this repo, lots of useful suggestions here!

I tried the bit on [L46-50](https://github.com/anki-code/awesome-xonshrc/blob/main/xonshrc#L46) but I noticed that if a xontrib is not installed I get no error. I copy my configuration onto multiple systems so this happens sometimes. Is there a way to make `xontrib load` more verbose so that I can at least get a notice that it failed?

**Comment by anki-code** [comment]
What about this:
```python
_xontribs = ['vox', 'asd']
if not !(xontrib load @(_xontribs)):
    printx("{RED}Not all xontribs are loaded!{RESET}")
```

Also I highly recommend you to use [the master way to install your RC](https://github.com/anki-code/xontrib-rc-awesome/blob/main/README.md#the-master-way-create-your-own-installable-rc-based-on-this-repo).

If you like the `awesome-xonshrc` click ⭐ on the repo.

**Comment by rpdelaney** [comment]
Yeah! Here's how I wound up doing it: https://github.com/rpdelaney/dotfiles/blob/main/home/.config/xonsh/rc.d/01-xontribs.xsh

I'm using the xonsh/rc.d/ pattern but I'm cribbing things from here too :) Thanks for the responsiveness!
